import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (React.createElement("html", { lang: "en" },
        React.createElement("body", { className: inter.className }, children)));
}
//# sourceMappingURL=layout.js.map